HTML = r'''<!doctype html>
<html lang="he" dir="rtl"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Film OS — כתובת אפס</title>
<style>
:root{font-family:Arial,sans-serif;color:#eaf5fa;background:#071019;--line:#294655;--card:#0d1b25;--soft:#102936;--accent:#9de8ff;--ok:#5ee09b}*{box-sizing:border-box}
body{margin:0;background:radial-gradient(circle at 90% 0,#17394e,#071019 45%);min-height:100vh}
header{padding:20px clamp(16px,4vw,42px);border-bottom:1px solid var(--line);background:#071019ed;position:sticky;top:0;z-index:3;display:flex;justify-content:space-between;gap:16px;align-items:center}
h1,h2,h3{margin:0}.sub,.meta{color:#96b4c2}.sub{margin-top:6px}.meta{font-size:13px}.wrap{max-width:1380px;margin:auto;padding:22px}
.tabs{display:flex;gap:8px;overflow:auto;margin-bottom:20px}.tabs button{white-space:nowrap}.panel{display:none}.panel.active{display:block}
button{border:0;border-radius:10px;padding:10px 14px;background:var(--accent);color:#061018;font-weight:700;cursor:pointer}button.secondary{background:#173343;color:#e8f7fc;border:1px solid #355667}button.danger{background:#482432;color:#ffdce6}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(285px,1fr));gap:14px}.card{background:var(--card);border:1px solid #223c4b;border-radius:16px;padding:16px;box-shadow:0 10px 28px #0002}.title{font-size:18px;font-weight:700;margin:7px 0 12px}
.row{display:flex;gap:9px;margin-top:10px}.row>*{flex:1}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px;flex-wrap:wrap}
input,select,textarea{width:100%;background:var(--soft);color:#fff;border:1px solid #345768;border-radius:9px;padding:10px;font:inherit}textarea{min-height:82px;resize:vertical}label{display:block;color:#b9d0da;font-size:13px;margin:11px 0 5px}
.badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#193849;color:#bceeff;font-size:12px}.badge.ok{background:#164632;color:#b8f4d1}.badge.warn{background:#513d18;color:#ffe5a5}
#modal{display:none;position:fixed;inset:0;background:#000c;align-items:center;justify-content:center;padding:14px;z-index:5}.dialog{width:min(1000px,100%);max-height:94vh;overflow:auto;background:#0b1822;border:1px solid #36596a;border-radius:18px;padding:20px}.modal-head{display:flex;justify-content:space-between;align-items:center;gap:12px;position:sticky;top:-20px;background:#0b1822;padding:10px 0;z-index:1}
.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 12px}.wide{grid-column:1/-1}.history{border-right:3px solid #31586c;padding:8px 12px;margin:10px 0;background:#0e222e;border-radius:8px}.empty{padding:24px;text-align:center;color:#91adba}.toast{position:fixed;left:20px;bottom:20px;background:#193849;border:1px solid #4e7c91;padding:12px 16px;border-radius:10px;display:none;z-index:8}
@media(max-width:700px){header{align-items:flex-start;flex-direction:column}.wrap{padding:14px}.fields{grid-template-columns:1fr}.wide{grid-column:auto}.row{flex-direction:column}}
</style></head><body>
<header><div><h1>AI Film OS — כתובת אפס</h1><div class="sub">גרסה 3 · סצנות, שוטים, גרסאות ורציפות</div></div><span class="badge ok">שמירה במסד הנתונים</span></header>
<main class="wrap">
<nav class="tabs"><button onclick="tab('scenes')">סצנות</button><button onclick="tab('shots')">שוטים</button><button onclick="tab('assets')">נכסים</button><button onclick="tab('qa')">רציפות QA</button></nav>
<section id="scenes" class="panel active"><div class="toolbar"><div><h2>סצנות</h2><div class="sub">כל סצנה מרכזת את השוטים השייכים אליה</div></div><button onclick="newScene()">סצנה חדשה</button></div><div id="scenesGrid" class="grid"></div></section>
<section id="shots" class="panel"><div class="toolbar"><div><h2>שוטים</h2><div id="shotSummary" class="sub"></div></div><div class="row" style="margin:0"><select id="sceneFilter" onchange="renderShots()"></select><button onclick="newShot()">שוט חדש</button></div></div><div id="shotsGrid" class="grid"></div></section>
<section id="assets" class="panel"><div class="toolbar"><div><h2>ספריית נכסים</h2><div class="sub">דמויות, לוקיישנים, אביזרים ולבוש</div></div><button onclick="assetForm()">נכס חדש</button></div><div id="assetsGrid" class="grid"></div></section>
<section id="qa" class="panel"><div class="toolbar"><div><h2>רציפות QA</h2><div class="sub">פערים מובנים לפי שוט, חומרה וסטטוס</div></div><select id="qaFilter" style="width:auto" onchange="loadQA()"><option value="">הכול</option><option>פתוח</option><option>בטיפול</option><option>נפתר</option><option>אושר כחריגה</option></select></div><div id="qaGrid" class="grid"></div></section>
</main>
<div id="modal"><div class="dialog"><div class="modal-head"><h2 id="modalTitle"></h2><button class="secondary" onclick="closeModal()">סגירה</button></div><div id="modalBody"></div></div></div><div id="toast" class="toast"></div>
<script>
const statuses=["מתוכנן","רפרנס","פרומפט מוכן","תמונה מאושרת","וידאו מוכן","וידאו מאושר","אודיו","סופי"];
const shotTypes=["","אקסטרים לונג","לונג","פול","מדיום","קלוז־אפ","אקסטרים קלוז־אפ","אינסרט"];
const qaCats=["דמות","לבוש","אביזר","לוקיישן","תאורה","צבע","כיוון מבט","תנועה","זמן","עלילה","אחר"];
let scenes=[],shots=[],assets=[];const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function api(url,opts={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opts});const d=await r.json();if(!r.ok)throw Error(d.detail||"שגיאה");return d}
function notify(t){toast.textContent=t;toast.style.display="block";setTimeout(()=>toast.style.display="none",2200)}
function tab(id){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');({scenes:loadScenes,shots:loadShots,assets:loadAssets,qa:loadQA}[id])()}
function openModal(title,html){modalTitle.textContent=title;modalBody.innerHTML=html;modal.style.display='flex'}function closeModal(){modal.style.display='none'}
async function loadScenes(){scenes=await api('/api/scenes');scenesGrid.innerHTML=scenes.length?scenes.map(s=>`<article class="card"><div class="meta">סצנה ${s.scene_number} · ${s.shot_count} שוטים · ${Number(s.duration_seconds||0).toFixed(1)} שנ׳</div><div class="title">${esc(s.title)}</div><p>${esc(s.synopsis)}</p><span class="badge">${esc(s.status)}</span><div class="row"><button onclick="editScene(${s.id})">עריכה</button><button class="secondary" onclick="openSceneShots(${s.id})">הצגת שוטים</button></div></article>`).join(''):'<div class="empty">עדיין אין סצנות</div>';return scenes}
function sceneFields(s={}){return `<div class="fields"><div><label>מספר סצנה</label><input id="fSceneNo" type="number" min="1" value="${esc(s.scene_number||scenes.length+1)}"></div><div><label>סטטוס</label><input id="fSceneStatus" value="${esc(s.status||'מתוכנן')}"></div><div class="wide"><label>שם הסצנה</label><input id="fSceneTitle" value="${esc(s.title||'')}"></div><div class="wide"><label>תקציר</label><textarea id="fSceneSynopsis">${esc(s.synopsis||'')}</textarea></div></div><div class="row"><button onclick="saveScene(${s.id||0})">שמירה</button></div>`}
function newScene(){openModal('סצנה חדשה',sceneFields())}function editScene(id){openModal('עריכת סצנה',sceneFields(scenes.find(x=>x.id===id)))}
async function saveScene(id){const data={scene_number:+fSceneNo.value,title:fSceneTitle.value,synopsis:fSceneSynopsis.value,status:fSceneStatus.value};await api(id?`/api/scenes/${id}`:'/api/scenes',{method:id?'PATCH':'POST',body:JSON.stringify(data)});closeModal();notify('הסצנה נשמרה');loadScenes()}
function openSceneShots(id){tab('shots');sceneFilter.value=String(id);renderShots()}
async function loadShots(){if(!scenes.length)await loadScenes();shots=await api('/api/shots');sceneFilter.innerHTML='<option value="">כל הסצנות</option>'+scenes.map(s=>`<option value="${s.id}">${s.scene_number} — ${esc(s.title)}</option>`).join('');shotSummary.textContent=`${shots.filter(x=>x.status==='סופי').length}/${shots.length} שוטים סופיים`;renderShots()}
function renderShots(){const filter=sceneFilter.value;const list=filter?shots.filter(s=>String(s.scene_id)===filter):shots;shotsGrid.innerHTML=list.map(s=>`<article class="card"><div class="meta">סצנה ${s.scene_number||'—'} · שוט ${s.shot_number||s.id} · ${s.duration_seconds?`${s.duration_seconds} שנ׳`:'משך לא הוגדר'}</div><div class="title">${esc(s.title)}</div><div><span class="badge">${esc(s.status)}</span> ${s.shot_type?`<span class="badge">${esc(s.shot_type)}</span>`:''}</div><p class="meta">${esc(s.action||s.notes||'אין תיאור פעולה')}</p><div class="row"><button onclick="editShot(${s.id})">פתיחת שוט</button><button class="secondary" onclick="generateShot(${s.id})">יצירת דף הפקה</button></div></article>`).join('')}
function newShot(){if(!scenes.length)return alert('יש ליצור סצנה תחילה');const preferred=sceneFilter.value||scenes[0].id;openModal('שוט חדש',`<div class="fields"><div><label>סצנה</label><select id="nScene">${scenes.map(s=>`<option value="${s.id}" ${String(s.id)===String(preferred)?'selected':''}>${s.scene_number} — ${esc(s.title)}</option>`).join('')}</select></div><div><label>מספר שוט בסצנה</label><input id="nNumber" type="number" min="1" value="1"></div><div class="wide"><label>שם השוט</label><input id="nTitle"></div></div><div class="row"><button onclick="saveNewShot()">יצירה והמשך לעריכה</button></div>`)}
async function saveNewShot(){const created=await api('/api/shots',{method:'POST',body:JSON.stringify({scene_id:+nScene.value,shot_number:+nNumber.value,title:nTitle.value})});closeModal();await loadShots();editShot(created.id)}
async function editShot(id){const s=await api(`/api/shots/${id}`);const field=(label,key,type='input')=>`<div class="${['title','composition','action','lighting','audio','prompt','negative_prompt','notes'].includes(key)?'wide':''}"><label>${label}</label>${type==='textarea'?`<textarea id="s_${key}">${esc(s[key]||'')}</textarea>`:`<input id="s_${key}" value="${esc(s[key]??'')}">`}</div>`;openModal(`שוט ${s.shot_number||s.id} — ${s.title}`,`<div class="fields">${field('שם השוט','title')}<div><label>סצנה</label><select id="s_scene_id">${scenes.map(x=>`<option value="${x.id}" ${x.id===s.scene_id?'selected':''}>${x.scene_number} — ${esc(x.title)}</option>`).join('')}</select></div><div><label>סטטוס</label><select id="s_status">${statuses.map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('')}</select></div><div><label>מספר שוט</label><input id="s_shot_number" type="number" value="${s.shot_number||s.id}"></div><div><label>משך בשניות</label><input id="s_duration_seconds" type="number" step="0.1" value="${s.duration_seconds||''}"></div><div><label>גודל שוט</label><select id="s_shot_type">${shotTypes.map(x=>`<option ${x===s.shot_type?'selected':''}>${x}</option>`).join('')}</select></div>${field('זווית מצלמה','camera_angle')}${field('עדשה במ״מ','lens_mm')}${field('תנועת מצלמה','camera_movement')}${field('קומפוזיציה','composition','textarea')}${field('פעולה','action','textarea')}${field('תאורה','lighting','textarea')}${field('פלטת צבעים','color_palette')}${field('אודיו','audio','textarea')}${field('הערות','notes','textarea')}${field('פרומפט','prompt','textarea')}${field('Negative prompt','negative_prompt','textarea')}</div><div class="row"><button onclick="saveShot(${id})">שמירת השוט</button><button class="secondary" onclick="chooseAssets(${id})">שיוך נכסים</button><button class="secondary" onclick="addMedia(${id})">תוצאת מדיה</button><button class="secondary" onclick="addQA(${id})">בדיקת QA</button></div><h3 style="margin-top:22px">היסטוריית גרסאות</h3>${historyHTML(s)}`)}
function historyHTML(s){const p=s.prompt_versions.map(v=>`<div class="history"><b>פרומפט v${v.version}</b> · ${esc(v.source)} · ${esc(v.created_at)}<div class="meta">${esc(v.prompt).slice(0,260)}</div></div>`).join('');const m=s.media_results.map(v=>`<div class="history"><b>${v.media_type==='image'?'תמונה':'וידאו'} v${v.version}</b> · ${esc(v.provider||'ללא ספק')} · ${esc(v.status)}<div><a href="${esc(v.url)}" target="_blank" style="color:#9de8ff">פתיחת התוצאה</a></div></div>`).join('');return p+m||'<div class="empty">עדיין אין גרסאות</div>'}
async function saveShot(id){const keys=['title','scene_id','status','shot_number','duration_seconds','shot_type','camera_angle','lens_mm','camera_movement','composition','action','lighting','color_palette','audio','notes','prompt','negative_prompt'];const data={};keys.forEach(k=>{const el=$(`s_${k}`);let v=el.value;if(['scene_id','shot_number','lens_mm'].includes(k))v=v?+v:null;if(k==='duration_seconds')v=v?+v:null;data[k]=v});await api(`/api/shots/${id}`,{method:'PATCH',body:JSON.stringify(data)});closeModal();notify('השוט נשמר ונוצרה גרסת פרומפט בעת הצורך');loadShots()}
async function generateShot(id){try{await api(`/api/shots/${id}/generate`,{method:'POST'});notify('דף ההפקה נוצר ונשמר כגרסה חדשה');loadShots()}catch(e){alert(e.message)}}
async function chooseAssets(id){assets=await api('/api/assets');const s=await api(`/api/shots/${id}`),selected=new Set(s.assets.map(a=>a.id));openModal('שיוך נכסים',`<div>${assets.map(a=>`<label><input style="width:auto" type="checkbox" name="asset" value="${a.id}" ${selected.has(a.id)?'checked':''}> ${esc(a.asset_type)} — ${esc(a.name)}</label>`).join('')}</div><div class="row"><button onclick="saveAssets(${id})">שמירה</button></div>`)}
async function saveAssets(id){const ids=[...document.querySelectorAll('input[name=asset]:checked')].map(x=>+x.value);await api(`/api/shots/${id}/assets`,{method:'PUT',body:JSON.stringify({asset_ids:ids})});closeModal();notify('הנכסים שויכו')}
async function addMedia(id){const versions=await api(`/api/shots/${id}/prompts`);openModal('הוספת תוצאת תמונה או וידאו',`<div class="fields"><div><label>סוג</label><select id="mType"><option value="image">תמונה</option><option value="video">וידאו</option></select></div><div><label>סטטוס</label><input id="mStatus" value="טיוטה"></div><div class="wide"><label>קישור לתוצאה</label><input id="mUrl"></div><div><label>ספק</label><input id="mProvider" placeholder="Magnific / Runway / אחר"></div><div><label>מודל</label><input id="mModel"></div><div class="wide"><label>גרסת פרומפט מקור</label><select id="mPrompt"><option value="">ללא שיוך</option>${versions.map(v=>`<option value="${v.id}">v${v.version} · ${esc(v.source)}</option>`).join('')}</select></div><div class="wide"><label>הערות</label><textarea id="mNotes"></textarea></div></div><div class="row"><button onclick="saveMedia(${id})">שמירת גרסה</button></div>`)}
async function saveMedia(id){await api(`/api/shots/${id}/media`,{method:'POST',body:JSON.stringify({media_type:mType.value,url:mUrl.value,provider:mProvider.value,model:mModel.value,prompt_version_id:mPrompt.value?+mPrompt.value:null,status:mStatus.value,notes:mNotes.value})});closeModal();notify('תוצאת המדיה נשמרה כגרסה חדשה')}
function addQA(id){openModal('בדיקת רציפות חדשה',`<div class="fields"><div><label>קטגוריה</label><select id="qCat">${qaCats.map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>חומרה</label><select id="qSeverity"><option>נמוך</option><option selected>בינוני</option><option>גבוה</option><option>חוסם</option></select></div><div class="wide"><label>הבעיה</label><textarea id="qIssue"></textarea></div><div><label>מה צריך להופיע</label><textarea id="qExpected"></textarea></div><div><label>מה נמצא בפועל</label><textarea id="qObserved"></textarea></div></div><div class="row"><button onclick="saveQA(${id})">שמירת בדיקה</button></div>`)}
async function saveQA(id){await api(`/api/shots/${id}/continuity`,{method:'POST',body:JSON.stringify({category:qCat.value,severity:qSeverity.value,issue:qIssue.value,expected:qExpected.value,observed:qObserved.value})});closeModal();notify('בדיקת הרציפות נשמרה')}
async function loadQA(){const q=await api('/api/continuity'+(qaFilter.value?`?status=${encodeURIComponent(qaFilter.value)}`:''));qaGrid.innerHTML=q.length?q.map(x=>`<article class="card"><div><span class="badge ${x.status==='נפתר'?'ok':x.severity==='חוסם'?'warn':''}">${esc(x.severity)}</span> <span class="badge">${esc(x.category)}</span></div><div class="title">${esc(x.issue)}</div><div class="meta">${esc(x.scene_title||'')} · שוט ${x.shot_number||x.shot_id}</div><p>צפוי: ${esc(x.expected||'—')}</p><p>נמצא: ${esc(x.observed||'—')}</p><div class="row"><select onchange="setQA(${x.id},this.value)"><option ${x.status==='פתוח'?'selected':''}>פתוח</option><option ${x.status==='בטיפול'?'selected':''}>בטיפול</option><option ${x.status==='נפתר'?'selected':''}>נפתר</option><option ${x.status==='אושר כחריגה'?'selected':''}>אושר כחריגה</option></select></div></article>`).join(''):'<div class="empty">אין בדיקות בסטטוס הזה</div>'}
async function setQA(id,status){await api(`/api/continuity/${id}`,{method:'PATCH',body:JSON.stringify({status})});notify('סטטוס QA עודכן');loadQA()}
async function loadAssets(){assets=await api('/api/assets');assetsGrid.innerHTML=assets.map(a=>`<article class="card"><span class="badge ${a.approved?'ok':''}">${esc(a.asset_type)}${a.approved?' · מאושר':''}</span><div class="title">${esc(a.name)}</div><p>${esc(a.description)}</p><div class="meta">${esc(a.visual_rules)}</div><div class="row"><button onclick="approveAsset(${a.id},${!a.approved})">${a.approved?'ביטול אישור':'אישור'}</button></div></article>`).join('')}
function assetForm(){openModal('נכס חדש',`<div class="fields"><div><label>סוג</label><select id="aType"><option>דמות</option><option>לוקיישן</option><option>אביזר</option><option>לבוש</option></select></div><div><label>שם</label><input id="aName"></div><div class="wide"><label>תיאור</label><textarea id="aDesc"></textarea></div><div class="wide"><label>כללים חזותיים</label><textarea id="aRules"></textarea></div><div class="wide"><label>קישור רפרנס</label><input id="aUrl"></div></div><div class="row"><button onclick="saveNewAsset()">הוספה</button></div>`)}
async function saveNewAsset(){await api('/api/assets',{method:'POST',body:JSON.stringify({asset_type:aType.value,name:aName.value,description:aDesc.value,visual_rules:aRules.value,reference_url:aUrl.value})});closeModal();notify('הנכס נוסף');loadAssets()}
async function approveAsset(id,value){await api(`/api/assets/${id}`,{method:'PATCH',body:JSON.stringify({approved:value})});loadAssets()}
loadScenes();
</script></body></html>'''
